### PR TITLE
Latest inf-ruby changes on github have changed inf-ruby-keys to inf-ruby-setup-keybindings

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Simple rename of a function in inf-ruby.

Commit in question
https://github.com/nonsequitur/inf-ruby/commit/86db14c3155ae72069fb0e4cbd635765c095331d

### CODE REVIEW

**Comment by daemianmack** [comment]
This bit me too. +1

**Comment by technomancy** [comment]
Does this break compatibility with the stable version of inf-ruby published at marmalade? Also, is the repo in question the canonical version of inf-ruby? Last I heard it was still being maintained out of Ruby's own repository.

**Comment by dgutov** [comment]
No, and yes. See where the "homepage" link from the [Marmalade page](http://marmalade-repo.org/packages/inf-ruby) leads.
`inf-ruby.el` in the Ruby repository is quite different, and it hasn't seen substantial changes in over 4 years.

**Comment by qizwiz** [comment]
Suggested workaround. Put this in your .emacs or init.el:
(defalias 'inf-ruby-keys 'inf-ruby-setup-keybindings)

**Comment by dgutov** [comment]
There's no reason to: the latest inf-ruby calls `inf-ruby-setup-keybindings` in an autoload.

The hook should just be removed.

**Comment by technomancy** [comment]
Thanks, but this project is no longer under deverlopment.

**Pull request closed without merging**
