### PR TITLE
Switch from idle-highlight to idle-highlight-mode.

### PR DESCRIPTION
**Pull request by nonsequitur**
http://marmalade-repo.org/packages/idle-highlight-mode

### CODE REVIEW

**Comment by technomancy** [comment]
Sorry for the delay; this looks great. Thanks!

I also switched to using this in the v2 branch.

**Comment by aguynamedben** [comment]
I think you need to do (maybe there is a faster way...) M-x package-list-packages, then navigate to idle-highlight-mode, then install from there.  Then Emacs will launch fine without complaining.  It seems like from the new notes in the README that the starter kit is going to integrate with the package manager.  I didn't even know there was a package manager.  Looks nice.

**Comment by HakubJozak** [comment]
Just FYI, the init failure appears only when you already have a setup version and the you pull new commits (the packages are downloaded only in fresh copy of starter-kit). I don't think it is so unusual workflow though - do you think there might be some solution that does not spit the error?

**Comment by lobo-tuerto** [comment]
I'm getting this error with emacs installed from Ubuntu repositories and _just pulled_ version of emacs-starter-kit.

And there is no idle-hightlight-mode in sight in M-x package-list-packages.

Any help will be appreciated.

**Comment by nonsequitur** [comment]
lobo-tuerto, that's because the [Marmalade package repository](http://marmalade-repo.org/) is currently offline.

**Comment by lobo-tuerto** [comment]
Oh, I see. Hope it's temporary (as in a few mins heh). Thank you.

**Comment by lobo-tuerto** [comment]
It's been offline for days, any word on when will it be back up online?

Or how can I install the missing packages?

**Comment by ghost** [comment]
Same error here. Are there any mirrors?

**Comment by technomancy** [comment]
I've contacted the maintainer twice about it. It's annoying because there's no reason the Node process dying should affect static file downloads, but what can you do. =(

You can use M-x package-install-file and a git checkout in the mean time.

**Comment by lobo-tuerto** [comment]
Uhh my emacs-fu is not strong enough to know what to do exactly. Could you elaborate a bit on the steps please?

**Comment by technomancy** [comment]
Sure, just check out the relevant repository via git and then invoke M-x package-install-file on the .el file you want.

**Comment by lobo-tuerto** [comment]
Thanks that did the trick! :)

**Comment by fracek** [comment]
Because of the frequent marmalade downtimes we should write that in the readme or in the wiki.

**Pull request merged**
